name: Deploy to Ec2 With Docker
  
on:  
  push:  
    branches:  
      - master
  
jobs:  
  build-and-deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src
          echo "${{ secrets.JWT_YML }}" | base64 --decode > src/main/resources/jwt.yml
          find src
      
      - name: Build with Gradle  
        working-directory: ./  
        run: |  
          chmod +x ./gradlew  
          ./gradlew bootJar 
  
      - name: Build Docker image
        working-directory: ./
        run: docker build -t ticketpaper2/logeat-backend:v1 .

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Push Docker Image to DockerHub
        run: docker push ticketpaper2/logeat-backend:v1        
      
      - name: EC2 SSH Login and Docker run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_SSH_KEY }} 
          script: |
            if ! type docker > /dev/null ; then
              sudo snap install docker
            fi
            sudo docker login --username ${{ secrets.DOCKER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ticketpaper2/logeat-backend:v1 
            sudo docker stop logeat-backend || true
            sudo docker rm -f logeat-backend || true

            sudo docker run -d --name logeat-backend -p 8081:8081 ticketpaper2/logeat-backend:v1
